CREATE TABLE IF NOT EXISTS `OrderDetail`(
    `ID` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `Order` INTEGER,
    `Product` INTEGER,
    `Quantity` INTEGER,
    CONSTRAINT FK_ORDERDETAIL_PRODUCT FOREIGN KEY(`Product`) references `Product`(ID),
    CONSTRAINT FK_ORDERDETAIL_ORDER FOREIGN KEY (`Order`) references `Order`(ID)
);