CREATE TABLE IF NOT EXISTS `Location`(
    `id` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `name` VARCHAR(50),
    `address` INTEGER,
    CONSTRAINT FK_LOCATION_ADDRESS FOREIGN KEY (`address`) REFERENCES `Address`(`id`)
    );