CREATE TABLE IF NOT EXISTS `Revenue`(
    `ID` INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `ID_location` INTEGER,
    `Date` DATE,
    `Sum` DECIMAL,
    CONSTRAINT FK_REVENUE_LOCATION FOREIGN KEY (`ID_location`) references `Location`(ID)
    );